// resources/js/components/cart/CartComponent.vue
<template>
    <div>
        <div class="cart_items">
            <ul class="cart_items_list">
                <!-- Cart Item -->
                <li
                    v-for="(cart, index) in carts"
                    class="cart_item item_list d-flex flex-lg-row flex-column align-items-lg-center align-items-start justify-content-lg-end justify-content-start"
                    style="width: 50%"
                >
                    <div
                        class="product d-flex flex-lg-row flex-column align-items-lg-center align-items-start justify-content-start mr-auto"
                    >
                        <RemoveComponent
                            :cartId="cart.id"
                            :productId="cart.product.id"
                            :sizeId="cart.size.id"
                            :qty="cart.qty"
                        />
                        <div>
                            <div class="product_image">
                                <img
                                    :src="'images/' + cart.product.image"
                                    alt=""
                                />
                            </div>
                        </div>
                        <div class="product_name_container">
                            <div class="product_name">
                                <a :href="'/product/' + cart.product.id">{{
                                    cart.product.name
                                }}</a>
                            </div>
                            <div class="product_text">
                                Second line for additional info
                            </div>
                        </div>
                    </div>
                    <div class="product_price product_text">
                        {{ cart.product.price }}
                    </div>
                    <div class="product_size product_text">
                        {{ cart.size.name }}
                    </div>
                    <div class="product_size product_text">{{ cart.qty }}</div>
                    <!-- NEW -->
                </li>
                <!-- Cart Item -->
            </ul>
        </div>
        <ClearComponent :carts="carts" />
    </div>
</template>

<script>
import axios from "axios";
import { cartNativeJsObj } from "../cartNative";
import RemoveComponent from "./RemoveComponent.vue";
import ClearComponent from "./ClearComponent.vue";

export default {
    data: function () {
        return {
            carts: window.carts,
        };
    },
    components: {
        RemoveComponent,
        ClearComponent,
    },
    mounted() {
        console.log(window.carts);

        this.$store.subscribe((mutation, state) => {
            console.log(mutation.type);

            if (mutation.type == "setCarts")
                this.handleCart(this.$store.getters.getCarts); //!!!getter
        });
    },
    methods: {
        handleCart(carts) {
            this.carts = carts;

            cartNativeJsObj.selector = "#lblCartCount";

            cartNativeJsObj.changeValueSelector(carts.length);
        },
    },
};
</script>

// resources/js/components/cart/CartComponent.jsx
﻿import React from "react";
import ReactDOM from "react-dom";
// import axios from "axios";
import RemoveDialog from "./RemoveComponent";
import ClearDialog from "./ClearComponent";

import { store } from "../reducer";
import { cartNativeJsObj } from "../cartNative";

class CartDialog extends React.Component {
    constructor(props) {
        super(props);
        this.handleCart = this.handleCart.bind(this);
        // this.clearCart = this.clearCart.bind(this);
        this.state = {
            carts: window.carts,
        };
    }

    componentDidMount() {
        console.log(this.state.carts);

        store.subscribe(() => this.handleStore(store.getState()));
    }

    handleStore(stories) {
        this.handleCart(stories.cartsReducer);
    }

    // clearCart(event) {
    //     event.preventDefault();
    //     let self = this; //!!!self - becouse axios
    //     axios
    //         .post("/clearall", {})
    //         .then(function (resp) {
    //             console.log(resp.data);

    //             self.handleCart(resp.data); //!!!self - becouse axios
    //         })
    //         .catch(function (resp) {
    //             console.log(resp);
    //             alert("Could not delete cart");
    //         });
    // }

    handleCart(carts) {
        this.setState({
            carts: carts,
        });
        // document.querySelector("#lblCartCount").innerText = carts.length;
        cartNativeJsObj.selector = "#lblCartCount";

        cartNativeJsObj.changeValueSelector(carts.length);
    }

    render() {
        return (
            <div>
                <div className="cart_items">
                    <ul className="cart_items_list">
                        {this.state.carts.map((item, key) => (
                            <li
                                key={key}
                                className="cart_item item_list d-flex flex-lg-row flex-column align-items-lg-center align-items-start justify-content-lg-end justify-content-start"
                                style={{ width: "50%" }}
                            >
                                <div className="product d-flex flex-lg-row flex-column align-items-lg-center align-items-start justify-content-start mr-auto">
                                    <RemoveDialog
                                        cartId={item.id}
                                        productId={item.product.id}
                                        sizeId={item.size.id}
                                        handleCart={this.handleCart}
                                    />
                                    <div>
                                        <div className="product_image">
                                            <img
                                                src={
                                                    "/images/" +
                                                    item.product.image
                                                }
                                                alt=""
                                            />
                                        </div>
                                    </div>
                                    <div className="product_name_container">
                                        <div className="product_name">
                                            <a
                                                href={
                                                    "/product/" +
                                                    item.product.id
                                                }
                                            >
                                                {item.product.name}
                                            </a>
                                        </div>
                                        <div className="product_text">
                                            Second line for additional info
                                        </div>
                                    </div>
                                </div>
                                <div className="product_price product_text">
                                    {item.product.price}
                                </div>
                                <div className="product_size product_text">
                                    {item.size.name}
                                </div>
                            </li>
                        ))}
                    </ul>
                </div>
                <ClearDialog
                    carts={this.state.carts}
                    handleCart={this.handleCart}
                />
            </div>
        );
    }
}

const elem = document.querySelector(".cart_block");

if (elem) {
    ReactDOM.render(<CartDialog />, elem);
}
